name: This repo fetches changes everytime there is a commit on the parent repo (linkedin/datahub), then build and publish the docs in 
      this repo.
on:
  push: #Uses the push event, so that the jobs run every time someone pushes a change to the rep
    branches:
      - master
    paths: 
      .github/workflows/documentation.yml
  release:
    types: [published, edited]
      
    # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  gh-pages:
    runs-on: ubuntu-latest #Configures the job to run on an Ubuntu Linux runner
    steps:
      - uses: actions/checkout@v2 #Checks out the repo and downloads it to the runner, to run actions against the code.
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1 
        with:
          java-version: 1.8
          
      - name: Deploy
        run: |
          git config --global user.email "saisarath.pu@gs.com"
          git config --global user.name "Sai Sarath"
          git remote add upstream https://github.com/linkedin/datahub.git          
          git checkout master
          git pull upstream master
          
      - name: Build Docs
        run: |
          ./gradlew --info docs-website:build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-website/build    
